{
  imports = [
    ./bluetooth.nix
    ./desktop.nix
    ./docker.nix
    ./fork.nix
    ./dualshock.nix
    ./libvirt.nix
    ./lsp-servers.nix
    ./menucalc.nix
    ./networking.nix
    ./nvidia.nix
    ./postgres.nix
    ./spicetify.nix
    ./stable.nix
    ./sunshine.nix
    ./zen-browser.nix
  ];
}
